name: Scheduled Playwright Tests

on:
  schedule:
    - cron: '0 17 * * *'   # Every Monday at 5:00 PM UTC
  workflow_dispatch:        # Allows manual run
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    # if: ${{ vars.RUN_SCHEDULED_TESTS == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run Playwright Tests
        run: mvn test
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload Playwright Report   # generates playwright reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Screenshots          #  uploads screenshots if test takes screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: test-results/