name: Scheduled Playwright Tests

on:
  schedule:
    - cron: '0 17 * * *'   # Every day at 5:00 PM UTC
  workflow_dispatch:        # Allows manual run
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04

    # if: ${{ vars.RUN_SCHEDULED_TESTS == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Playwright Browsers
        run: |
          chmod +x gradlew
          ./gradlew testClasses

      - name: Run Playwright Tests
        run: ./gradlew clean test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Upload Playwright Report   # generates playwright reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Screenshots          #  uploads screenshots if test takes screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: test-results/

env:
  HEADLESS: "true"